[package]
name = "client_capture"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
image = "0.25.1"
tokio = { version = "1.37.0", features = ["full"] }
windows-capture = "1.1.8"
window_inspector = { git = "https://github.com/enximi/window_inspector" }
log = "0.4.21"
